<style>


	*{

	margin-left:35px;

}
body{
}
li.valor{
	margin-button:0px;
	margin-left:35px;
	font-size:50px;
	list-style-type:none;
	display:inline-block;
	width:100px;
	color:#656360;
	transition:0.5s;
  background-color: #FFF;
	padding-left: 50px;
	padding-right: 125px;
	padding-bottom: 250px;
	padding-top: 200px;
  border:1px solid #00ffd0;
  font-family: Helvetica, Arial, sans-serif;	
	
}
li.valor2{
	margin-top:0px;
	margin-left:35px;
	font-size:18px;
	list-style-type:none;
	display:inline-block;
	width:100px;
	background-color:#00ffd0;
	color:#FFF;
	transition:0.5s;
	padding-left: 50px;
	padding-right: 125px;
	padding-bottom: 10px;
	padding-top: 40px;
	border:1px solid #d5d5d5;
   font-family: Helvetica, Arial, sans-serif; 
	
}
li.tipo {
	margin-top:65px;
	margin-left:35px;
	margin-button:0;
	font-size:20px;
	list-style-type:none;
	display:inline-block;
	width:100px;
	background-color:#00ffd0;
	color:#FFF;
	transition:0.5s;
	padding-left: 50px;
	padding-right: 125px;
	padding-top: 20px;
	border:1px solid #d5d5d5;
   font-family: Helvetica, Arial, sans-serif; 
}
li.valor:hover{
	background-color:#333;
	padding-left: 50px;
	padding-right: 125px;
    	padding-top: 300px;
      color:#00ffd0;	
	
}


.menu{
	background-color:#FCF;
	height:500px;
}

a{
	text-decoration:none;
}
 .botao01{
background: -webkit-linear-gradient(bottom, orange, orange 70%);
     background: -moz-linear-gradient(bottom, #E0E0E0, #F9F9F9 70%);
     background: -o-linear-gradient(bottom, #E0E0E0, #F9F9F9 70%);
     background: -ms-linear-gradient(bottom, #E0E0E0, #F9F9F9 70%);
     background: linear-gradient(bottom, #E0E0E0, #F9F9F9 70%);
     border: 1px solid black;
     border-radius: 3px;
     box-shadow: 0 3px 0 rgba(0, 0, 0, .3),
                   0 2px 7px rgba(0, 0, 0, 0.2);
     color: black;
     display: block;
     font-family: "Trebuchet MS";
     font-size: 14px;
     font-weight: bold;
     line-height: 25px;
     text-align: center;
     text-decoration: none;
     text-transform: uppercase;
     text-shadow:1px 1px 0 #FFF;
     padding: 5px 15px;
     position: relative;
     width: 120px;
    }
    .botao01:before{
     border: 1px solid black;
     border-radius: 3px;
     box-shadow: inset 0 -2px 12px -4px rgba(70, 70, 70, .2),
                   inset 0 3px 2px -1px rgba(255, 255, 255, 1);
     content: "";
     bottom: 0;
     left: 0;
     right: 0;
     top: 0;
     padding: 5px;
     position: absolute;
    }
 
    .botao01:after{
     border-radius: 2px;
     content: "";
     bottom: 15px;
     left: 0px;
     right: 0px;
     top: 0px;
     position: absolute;
    }
     .botao01:active{
     box-shadow: inset 0 0 7px rgba(0, 0, 0, .2);
     top: 4px;
    }
    .botao01:active:before{
     border: none;
     box-shadow:none;
    }
</style>
<center><ul>
<li class="tipo"><center>NORMAL</center></li>
<li class="tipo"><center>ESPECIAL </center></li>
<li class="tipo"><center>TOP </center></li>
<li class="valor"> <center>Plano Mensal</center></li>
<li class="valor"> <center>Plano Semestral </center></li>
<li class="valor"> <center>Plano Anual</center></li></ul>

<li class="valor2"><p>R$10,00/mês</p><button id="mes" class="botao01" onclick="pagamentoMensal()">Assinar</button><br>
<form id="item1" action="https://sandbox.pagseguro.uol.com.br/checkout/v2/payment.html" method="post" onsubmit="PagSeguroLightbox(this); return false;">
<input type="hidden" id="code1" name="code" value="" />
<input type="hidden" id="usuario1" value="<?php echo $_SESSION['id'];?>"/>
</form>
<script type="text/javascript" src="https://stc.sandbox.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.lightbox.js"></script>
<center><img src="content/site/img/load-indicator.gif" id="loading1" style="visibility: hidden"></center>
</li>

<li class="valor2"><p>R$25,00/mês</p><button id="seis" class="botao01" onclick="pagamentoSemestral()">Assinar</button><br>
<form id="item2" action="https://sandbox.pagseguro.uol.com.br/checkout/v2/payment.html" method="post" onsubmit="PagSeguroLightbox(this); return false;">
<input type="hidden" id="code2" name="code" value="" />
<input type="hidden" id="usuario2" value="<?php echo $_SESSION['id'];?>"/>
</form>
<script type="text/javascript" src="https://stc.sandbox.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.lightbox.js"></script>
<center><img src="content/site/img/load-indicator.gif" id="loading2" style="visibility: hidden"></center>
</li>


<li class="valor2"><p>R$50,00/mês</p><button class="botao01" id="anual" onclick="pagamentoAnual()">Assinar</button><br>
<form id="item3" action="https://sandbox.pagseguro.uol.com.br/checkout/v2/payment.html" method="post" onsubmit="PagSeguroLightbox(this); return false;">
<input type="hidden" id="code3" name="code" value="" />
<input type="hidden" id="usuario3" value="<?php echo $_SESSION['id'];?>"/>
</form>
<script type="text/javascript" src="https://stc.sandbox.pagseguro.uol.com.br/pagseguro/api/v2/checkout/pagseguro.lightbox.js"></script>
<center><img src="content/site/img/load-indicator.gif" id="loading3" style="visibility: hidden"></center>
 </li>	

</ul></center>

<script>
function pagamentoAnual(){
    var data = new Date();
    var dataFormatada = ("0" + data.getDate()).substr(-2) + "/" 
    + ("0" + (data.getMonth() + 1)).substr(-2) + "/" + data.getFullYear();
 $.ajax({
   url : 'model/SalvarPagamento.php',
   dataType : 'html',
   type : 'POST',
   data : { Usuario_id_userpgto : $('#usuario3').val(),plano : 'TOP',valor_pgto : '50,00',data_pedido : dataFormatada },
   beforeSend : function () {
         $('#loading3').css("visibility","visible");
   },
   success : function(retorno){
        $.post('model/PagSeguro.php',{idPedido:retorno,plano : 'TOP',valor_pgto : '50.00'},function(data){
            //alert(data);
       $('#code3').val(data);
       $('#item3').submit();
    });
         $('#loading3').css("visibility","hidden");
   },
   error : function(a,b,c){
       $('#loading3').css("visibility","hidden");
       alert('Erro: '+a[status]+' '+c);
   }
});

 }
 function pagamentoMensal(){
    var data = new Date();
    var dataFormatada = ("0" + data.getDate()).substr(-2) + "/" 
    + ("0" + (data.getMonth() + 1)).substr(-2) + "/" + data.getFullYear();
 $.ajax({
   url : 'model/SalvarPagamento.php',
   dataType : 'html',
   type : 'POST',
   data : { Usuario_id_userpgto : $('#usuario1').val(),plano : 'NORMAL',valor_pgto : '10,00',data_pedido : dataFormatada },
   beforeSend : function () {
         $('#loading1').css("visibility","visible");
   },
   success : function(retorno){
        $.post('model/PagSeguro.php',{idPedido:retorno,plano : 'NORMAL',valor_pgto : '10.00'},function(data){
       $('#code1').val(data);
       $('#item1').submit();
    });
         $('#loading1').css("visibility","hidden");
   },
   error : function(a,b,c){
       $('#loading1').css("visibility","hidden");
       alert('Erro: '+a[status]+' '+c);
   }
});
 }
 function pagamentoSemestral(){
    var data = new Date();
    var dataFormatada = ("0" + data.getDate()).substr(-2) + "/" 
    + ("0" + (data.getMonth() + 1)).substr(-2) + "/" + data.getFullYear();
 $.ajax({
   url : 'model/SalvarPagamento.php',
   dataType : 'html',
   type : 'POST',
   data : { Usuario_id_userpgto : $('#usuario2').val(),plano : 'ESPECIAL',valor_pgto : '25,00',data_pedido : dataFormatada },
   beforeSend : function () {
         $('#loading2').css("visibility","visible");
   },
   success : function(retorno){
        $.post('model/PagSeguro.php',{idPedido:retorno,plano : 'ESPECIAL',valor_pgto : '25.00'},function(data){
       $('#code2').val(data);
       $('#item2').submit();
    });
         $('#loading2').css("visibility","hidden");
   },
   error : function(a,b,c){
       $('#loading2').css("visibility","hidden");
       alert('Erro: '+a[status]+' '+c);
   }
});
 }
</script>
