<a href="usuario/" class="botao01">Voltar</a>

<table width=100% border="1px" bgcolor="black">
  <tr>
    <td width="101" height="40"  bgcolor="white" ><center>ID</center></td>
    <td width="113"><center>NOME</center></td>
    <td width="113"><center>ENDEREÇO</center></td>
    <td width="85"><center>TELEFONE</center></td>
    <td width="85"><center>TIPO</center></td>
    <td width="85"><center>CNPJ</center></td>
    <td width="85"><center>DATA DE INICIO</center></td>
    <td width="85"><center>DATA DE ENCERRAMENTO</center></td>
    <td width="85"><center>STATUS</center></td>
    <td width="85"><center>EMAIL</center></td>
    <td width="85"><center>CEP</center></td>
    <td width="85"><center>NÚMERO DO ENDEREÇO</center></td>
    <td width="85"><center>COMPLEMENTO</center></td>
    <td width="85"><center>BAIRRO</center></td>
    <td width="85"><center>CIDADE</center></td>
    <td width="85"><center>SITE</center></td>
    <td width="85"><center></center></td>

  </tr>
   <?php 
        //var_dump($view_list);
        if(count($view_list)>0):?>
        <?php foreach ($view_list as $li):?>
  <tr>
    <td height="40" bgcolor="white "><?php echo $li->id_par;?></td>
    <td bgcolor="white"><?php echo  $li->nome_par;?></td>
    <td bgcolor="white "><?php echo $li->end_par;?></td>
    <td bgcolor="white "><?php echo $li->tel_par;?></td>
    <td bgcolor="white "><?php echo $li->tipo_par;?></td>
    <td bgcolor="white "><?php echo $li->cnpj_par;?></td>
    <td bgcolor="white "><?php echo $li->data_inicio;?></td>
    <td bgcolor="white "><?php echo $li->data_enc;?></td>
    <td bgcolor="white "><?php echo $li->status_par;?></td>
    <td bgcolor="white "><?php echo $li->email_par;?></td>
    <td bgcolor="white "><?php echo $li->cep_par;?></td>
    <td bgcolor="white "><?php echo $li->numEndereco_par;?></td>
    <td bgcolor="white "><?php echo $li->complemento_par;?></td>
    <td bgcolor="white "><?php echo $li->bairro_par;?></td>
    <td bgcolor="white "><?php echo $li->cidade_par;?></td>
    <td bgcolor="white "><?php echo $li->site_par;?></td>
    </tr>
        <?php endforeach;?>
        <?php endif;?>
    </tbody>
</table>



