<div class="content">
<a href="atracoes" class="botao01">Voltar</a>
</div>
    <form enctype="multipart/form-data" method="POST" action="atracoes/saveimg">
        <input type="hidden" name="url" value="content/site/img/imgAtracoes/"/>
        <input type="hidden" name="id_alb" value="<?php echo $view_return;?>"/>
        <input type="hidden" name="tipo" value="atracao"/>
			<input type="file" name="arquivo[]" multiple="multiple" /><br><br>
			<input name="enviar" type="submit" value="Enviar" class="botao01">
		</form>
