<style>
    .x{
        position: absolute;
        cursor: pointer;
    }
</style>
<div class="content">
<a href="eventos" class="botao01">Voltar</a>
</div>
<form action="eventos/save" method="POST" enctype="multipart/form-data">
<br><br>
<center></center><label><h2>ID:</h2></label><input type="text" name="cod_evento" value="<?php echo $view_dados->cod_evento;?>" readonly class="input-class"><br>
   <input type="hidden" name="url" value="content/site/img/imgevento/"/>
   <input type="hidden" name="id_album" value="<?php echo $view_dados->id_album;?>"/>
   <label for="txtNome" ><h2>Nome:</h2></label> <input type="text"  value="<?php echo $view_dados->nome_evento;?>" id="txtNome"  name="nome_evento" class="input-class" /><br>
            <label for="data" ><h2>Data:</h2></label> <input type="date"  value="<?php echo $view_dados->data_evento;?>" id="data" name="data_evento" class="input-class" /><br>
          <?php if($view_dados->cod_evento != '') {?> 
            <label for="hora" ><h2>Horario:</h2></label> <input type="text"  value="<?php echo $view_dados->hr_evento;?> "id="hora" name="hr_evento"  class="input-class"/><br>
 <?php }else{?>
           <label for="hora" ><h2>Horario:</h2></label> <input type="time"  value="<?php echo $view_dados->hr_evento;?> "id="hora" name="hr_evento" class="input-class"/><br> 
 <?php }?>
            <label for="txtLoc" ><h2>Local:</h2></label> <input type="text"  value="<?php echo $view_dados->local_evento;?>" id="txtLoc" name="local_evento" class="input-class" /><br>
            <label for="txtDesc" ><h2>Descrição:</h2></label><textarea rows="4" cols="50" name="desc_evento" id="txtDesc" class="input-class" ><?php echo $view_dados->desc_evento;?></textarea><br><br>
            <?php if($view_dados->cod_evento != '') {?> 
           <?php foreach ($view_dados->caminho_img as $val){ ?>
            <?php if($val->id_img != 186){  ?>
                      <img class="x" id="<?php echo $val->id_img;?>" alt="<?php echo $val->id_img;?>" src="../content/site/img/mono-icons/stop32.png" />                               
  <?php } ?>
            <img id="img<?php echo $val->id_img;?>" src="../<?php echo $val->caminho_img; ?>" alt="alt text" width="200" height="200"/>
            
                                                  
                                                        <?php } ?>
           <br>
           <?php } ?>
       <script>
               $(".x").click(function(){
      
         var altx = $(this).attr("alt");
          var selector = '#'+'img'+altx;
          var alt = '#'+altx;
      $.post("../model/excluirimg.php",{altx:altx}, function(resultado){
         $(alt).hide(); 
        $(selector).hide();
        
        
  });
         
     });
         

     </script>
    <center><button type="submit" id="btnEnviar" class="botao01">Enviar</button></center>
   <br>
</form>
