		<div class="loginbox">
		<img src="content/admin/img/user.png" class="user">
		<h2>Login</h2>
		<form action="admin/sessao/validar" method="POST">
				<p>Usuário</p>
				<input type="text" name="usuario" placeholder="Digite seu Usuário"/>
				<p>Senha</p>
				<input type="password" name="senha" placeholder="*******"/>
				<input type="submit" name="btnfazer" value="Entrar"/>&nbsp;
				
				
    <p id="msg"><?php if(isset($_SESSION['msg'])){ echo $_SESSION['msg']; unset ($_SESSION['msg']); }?></p>
</form>				
</div>	