 <script>
                                    $(document).ready(function(){
                                         $("li").removeClass('current-menu-item');
                                        $(".entrar").addClass('current-menu-item');
 });
function VerificaCPF () {
   // event.preventdefault();
if (vercpf(document.frmcpf.cpf_user.value)) 
{return true;}else 
{errors="1";if (errors) alert('CPF NÃO VÁLIDO');
document.retorno = (errors == '');}return false;}
function vercpf (cpf_user) 
{if (cpf_user.length != 11 || cpf_user == "00000000000" || cpf_user == "11111111111" || cpf_user == "22222222222" || cpf_user == "33333333333" || cpf_user == "44444444444" || cpf_user == "55555555555" || cpf_user == "66666666666" || cpf_user == "77777777777" || cpf_user == "88888888888" || cpf_user == "99999999999")
return false;
add = 0;
for (i=0; i < 9; i ++)
add += parseInt(cpf_user.charAt(i)) * (10 - i);
rev = 11 - (add % 11);
if (rev == 10 || rev == 11)
rev = 0;
if (rev != parseInt(cpf_user.charAt(9)))
return false;
add = 0;
for (i = 0; i < 10; i ++)
add += parseInt(cpf_user.charAt(i)) * (11 - i);
rev = 11 - (add % 11);
if (rev == 10 || rev == 11)
rev = 0;
if (rev != parseInt(cpf_user.charAt(10)))
return false;return true;}

</script>
<form name="frmcpf" id="frmcpf" action="site/cadastroUsuario/save" method="POST">
<br>
<br>
<center><div class="box1"><h1>CADASTRE-SE</div><br></center>
<br>
<br>
<input type="hidden" name="id_user" value="" >
<br>
<label for="txtNome" ></label>
<center><h4>Nome:</h4> <input type="text" class="input-class" required id="txtNome" placeholder="Digite seu Nome" name="nome_user" class="box7" size="25px"/><br><br></center>
<label for="txtSobrenome" ></label>
<center><h4>Sobrenome:</h4> <input type="text" class="input-class" required id="txtSobrenome" placeholder="Digite seu Sobrenome" name="sobrenome_user" class="box7" size="17px"/><br><br></center>
<label for="numFone"></label>
<center><h4>Telefone:</h4> <input type="text" maxlength="11" class="input-class" id="numFone" placeholder="Digite seu Telefone" required  name="tel_user" class="box7" size="40px" /><br><br></center>
<label for="txtEmail" ></label>
<center><h4>E-mail:</h4> <input type="text" class="input-class" id="txtEmail" placeholder="Digite seu E-mail" required name="email_user" class="box7" size="22"/><br><br></center>
<label for="numCpf" ></label>
<center><h4>CPF: </h4><input type="text" maxlength="11" required id="NrCpf" class="input-class" placeholder="Digite seu CPF" name="cpf_user" class="box7" size="22"><br><br></center>
<label for="numCEP"></label>
<center><h4>CEP:</h4><input type="text" id="CEP" maxlength="8" class="input-class" name="cep_user" class="box7" placeholder="Digite seu CEP" onblur="pesquisacep(this.value);"/><br><br></center>
<label for="enviar"></label>
<center><h4>Logradouro:</h4> <input readonly  type="text" id="rua"  class="input-class" name="end_user" placeholder="Digite seu Logradouro" /><br><br></center>
<label for="numEnd"></label>
<center><h4>Numero:</h4> <input type="number" id="numEnd"  class="input-class" name="numEndereco_user" class="box7" placeholder="Digite o Numero"/><br><br></center>
<label for="complemento"></label>
<center><h4>Complemento:</h4> <input type="text" id="txtComplemento"  class="input-class" name="complemento_user" placeholder="Digite seu Complemento" class="box7" placeholder="Digite o complemento"/><br><br></center>
<label for="bairro"></label>
<center><h4>Bairro:</h4> <input readonly  type="text" id="bairro"  name="bai_user" class="input-class" placeholder="Digite seu Bairro" class="box7" /><br><br></center>
<label for="Cidade"></label>
<center><h4>Cidade:</h4> <input readonly  type="text" id="cidade"  name="cid_user" class="input-class" placeholder="Digite sua Cidade" class="box7"/><br><br></center>
<center><h4>Senha:</h4><input type="password" size="13" id="senha" name="senha_user" class="input-class" required id="enviar" placeholder="Digite sua Senha"  class="box7" /><br><br></center>
<center><h4>Comfirmar Senha:</h4><input type="password" size="13"  id="comfirma" class="input-class" required id="enviar" placeholder="Digite sua Senha"  class="box7" /><br><br></center>
     <center><button type="submit" id="btnEnviar" class="send" onclick="return validaform();">Enviar</button></center>
   <br>
     <script type="text/javascript">$("#numFone").mask("(00) 0000-00009");</script>
     <script type="text/javascript" >
    
    function limpa_formulário_cep() {
            //Limpa valores do formulário de cep.
            document.getElementById('rua').value=("");
            document.getElementById('bairro').value=("");
            document.getElementById('cidade').value=("");
            document.getElementById('uf').value=("");
            document.getElementById('ibge').value=("");
    }

    function meu_callback(conteudo) {
        if (!("erro" in conteudo)) {
            //Atualiza os campos com os valores.
            document.getElementById('rua').value=(conteudo.logradouro);
            document.getElementById('bairro').value=(conteudo.bairro);
            document.getElementById('cidade').value=(conteudo.localidade);
            document.getElementById('uf').value=(conteudo.uf);
            document.getElementById('ibge').value=(conteudo.ibge);
        } //end if.
        else {
            //CEP não Encontrado.
           // limpa_formulário_cep();
             document.getElementById('rua').value=('CEP não Encontrado');
            document.getElementById('bairro').value=('CEP não Encontrado');
            document.getElementById('cidade').value=('CEP não Encontrado');
           
        }
    }
        
    function pesquisacep(valor) {

        //Nova variável "cep" somente com dígitos.
        var cep = valor.replace(/\D/g, '');

        //Verifica se campo cep possui valor informado.
        if (cep != "") {

            //Expressão regular para validar o CEP.
            var validacep = /^[0-9]{8}$/;

            //Valida o formato do CEP.
            if(validacep.test(cep)) {

                //Preenche os campos com "..." enquanto consulta webservice.
                document.getElementById('rua').value="...";
                document.getElementById('bairro').value="...";
                document.getElementById('cidade').value="...";
               

                //Cria um elemento javascript.
                var script = document.createElement('script');

                //Sincroniza com o callback.
                script.src = '//viacep.com.br/ws/'+ cep + '/json/?callback=meu_callback';

                //Insere script no documento e carrega o conteúdo.
                document.body.appendChild(script);

            } //end if.
            else {
                //cep é inválido.
               // limpa_formulário_cep();
                
            document.getElementById('rua').value=("Formato de CEP inválido");
            document.getElementById('bairro').value=("Formato de CEP inválido");
            document.getElementById('cidade').value=("Formato de CEP inválido");
            }
        } //end if.
        else {
            //cep sem valor, limpa formulário.
            limpa_formulário_cep();
        }
    };

    </script>
    <script type="text/javascript">
         function senhas(){
            var senha1 = document.getElementById('senha').value;
            var senha2 = document.getElementById('comfirma').value;
        if(senha1 != senha2){
            alert("senhas não conferem");
            return false;
        }
    }
    function verificacep(){
if( document.getElementById('rua').value == "Formato de CEP inválido" || document.getElementById('rua').value == "CEP não Encontrado" ){
    alert("CEP não atente a especificacao");
    return false;
}
}
    function validaform(){
        var senha = senhas();
        var cep   = verificacep();
        var cpf  = VerificaCPF();

        if(senha == false || cep == false || cpf == false){
            return false;
        }  
    }

    </script>
</form>  