<?php
date_default_timezone_set('America/Sao_Paulo');
// CRIA UMA VARIAVEL E ARMAZENA A HORA ATUAL DO FUSO-HORÀRIO DEFINIDO (BRASÍLIA)
 $dataLocal = date('d/m/Y H:i:s');
?>
<form name="frmCadastro" action="site/parceiro/save" method="POST" enctype="multipart/form-data">
<br>
<label for="txtNome" ></label>
<center><h3>Nome da Empresa:</h3> <input type="text" class="input-class" required id="txtNome" placeholder="Digite seu Nome" name="nome_par" class="box7" size="25px"/><br><br></center>
<label for="txtSobrenome" ></label>
<label for="numFone"></label>
<center><h3>Telefone: </h3><input type="text" maxlength="11" class="input-class" id="numFone" placeholder="Digite seu Telefone" required  name="tel_par" class="box7" size="40px" /><br><br></center>
<label for="txtEmail" ></label>
<center><h3>E-mail:</h3> <input type="email" class="input-class" id="txtEmail" placeholder="Digite seu E-mail" required name="email_par" class="box7" size="22"/><br><br></center>
<label for="numCpf" ></label>
<center><h3>Site:</h3> <input type="text" class="input-class"  name="site_par" /><br><br></center>
<center><h3>CNPJ:</h3> <input type="number" class="input-class" required id="numCpf" placeholder="Digite seu CNPJ" name="cnpj_par" class="box7" size="22"><br><br></center>
        <center><input type="hidden" class="input-class" id="txtEnd" name="data_inicio" value="<?php echo $dataLocal;?>"/><br></center><br>
<label for="numCEP"></label>
<center><h3>CEP:</h3> <input type="text" maxlength="8" class="input-class" id="CEP" name="cep_par" class="box7" placeholder="Digite seu CEP" onblur="pesquisacep(this.value);"/><br><br></center>
<label for="enviar"></label>
<center><h3>Logradouro: </h3><input readonly type="text"  class="input-class" id="rua"  name="end_par" class="box7" /><br><br></center>
<label for="numEnd"></label>
<center><h3>Numero:</h3> <input type="number" class="input-class" id="numEnd"  name="numEndereco_par" class="box7" placeholder="Digite o Numero"/><br><br></center>
<label for="complemento"></label>
<center><h3>Complemento: </h3><input type="text" class="input-class" id="txtComplemento"  name="complemento_par" class="box7" placeholder="Digite o complemento"/><br><br></center>
<label for="bairro"></label>
<center><h3>Bairro:</h3> <input readonly type="text" class="input-class" id="bairro"  name="bairro_par" class="box7"/><br><br></center>
<label for="Cidade"></label>
<center><h3>Cidade:</h3> <input readonly type="text" class="input-class" id="cidade"  name="cidade_par" class="box7"/><br><br></center>
<center><h3> Senha:</h3><input type="password" class="input-class" size="13" id="senha" name="senha_par" required id="enviar" placeholder="Digite sua Senha"  class="box7" /><br><br></center>
<center><h3>Confirmar Senha:</h3><input type="password" class="input-class"  size="13"  required id="comfirma" placeholder="Digite sua Senha"  class="box7" /><br><br></center>
<h3>Adicione o logo da empresa</h3>
<center><input id="logo" type="file" name="logo" /><br><br></center>
<br>
     <center><button type="submit" class="send" id="btnEnviar" onclick="return validaform();">Enviar</button></center>
   <br>

     <script type="text/javascript">$("#numFone").mask("(00) 0000-00009");</script>
      <script type="text/javascript" >
    
    function limpa_formulário_cep() {
            //Limpa valores do formulário de cep.
            document.getElementById('rua').value=("");
            document.getElementById('bairro').value=("");
            document.getElementById('cidade').value=("");
            document.getElementById('uf').value=("");
            document.getElementById('ibge').value=("");
    }

    function meu_callback(conteudo) {
        if (!("erro" in conteudo)) {
            //Atualiza os campos com os valores.
            document.getElementById('rua').value=(conteudo.logradouro);
            document.getElementById('bairro').value=(conteudo.bairro);
            document.getElementById('cidade').value=(conteudo.localidade);
            document.getElementById('uf').value=(conteudo.uf);
            document.getElementById('ibge').value=(conteudo.ibge);
        } //end if.
        else {
            //CEP não Encontrado.
           // limpa_formulário_cep();
             document.getElementById('rua').value=('CEP não Encontrado');
            document.getElementById('bairro').value=('CEP não Encontrado');
            document.getElementById('cidade').value=('CEP não Encontrado');
           
        }
    }
        
    function pesquisacep(valor) {

        //Nova variável "cep" somente com dígitos.
        var cep = valor.replace(/\D/g, '');

        //Verifica se campo cep possui valor informado.
        if (cep != "") {

            //Expressão regular para validar o CEP.
            var validacep = /^[0-9]{8}$/;

            //Valida o formato do CEP.
            if(validacep.test(cep)) {

                //Preenche os campos com "..." enquanto consulta webservice.
                document.getElementById('rua').value="...";
                document.getElementById('bairro').value="...";
                document.getElementById('cidade').value="...";
               

                //Cria um elemento javascript.
                var script = document.createElement('script');

                //Sincroniza com o callback.
                script.src = '//viacep.com.br/ws/'+ cep + '/json/?callback=meu_callback';

                //Insere script no documento e carrega o conteúdo.
                document.body.appendChild(script);

            } //end if.
            else {
                //cep é inválido.
               // limpa_formulário_cep();
                
            document.getElementById('rua').value=("Formato de CEP inválido");
            document.getElementById('bairro').value=("Formato de CEP inválido");
            document.getElementById('cidade').value=("Formato de CEP inválido");
            }
        } //end if.
        else {
            //cep sem valor, limpa formulário.
            limpa_formulário_cep();
        }
    };

    </script>
      <script type="text/javascript">
         function senhas(){
            var senha1 = document.getElementById('senha').value;
            var senha2 = document.getElementById('comfirma').value;
        if(senha1 != senha2){
            alert("senhas não conferem");
            return false;
        }
    }
    function verificacep(){
if( document.getElementById('rua').value == "Formato de CEP inválido" || document.getElementById('rua').value == "CEP não Encontrado" ){
    alert("CEP não atente a especificacao");
    return false;
}
}
    function validaform(){
        var senha = senhas();
        var cep   = verificacep();

        if(senha == false || cep == false){
            return false;
        }  
    }
    </script>
</form>  
