<?php if($view_return == 'Enviado com sucesso'){ ?>
<center><h3>Cadastrado com sucesso</h3></center>
<br>
<br>
<br>
<!--<center><h3><?php echo $view_return;?></h3></center>-->
<br>
<br>
<center><img src="content/site/img/parceiro.png" width="500" height="400"></center>
<!--<center><p>Cadastrado com id:<?php //echo $view_id;?></p></center>-->
<br>
<br>
<center><p>Os Administradores estao validando as informacoes</p></center><br>
<center><p>Aguarde nosso retorno</p></center>
<br>
<br>
<br>
<?php } else {?>
<center><h3><?php echo $view_return;?></h3></center>   
<?php } ?>


