<div class="content">
<a href="notificacoes/" class="botao01">Voltar</a>
														</div>
						<p>
						NOME: <?php echo $view_list[0]->name;?>
                                               
						</p>
						
						<p>
					EMAIL:
	 <?php echo  $view_list[0]->email;?>
						</p>
						
						<p>
		NOME DA EMPRESA:
		 <?php echo   $view_list[0]->web;?>
						</p>
						
						<p>
							MENSAGEM:
				 <?php echo  $view_list[0]->comments;?>
						</p>
               
      
 

