<div class="content">
<a href="notificacoes/" class="botao01">Voltar</a>
</div>
<table width=100% border="1px" bgcolor="black">
  <tr>
    <td width="101" height="40" bgcolor="white"><center>ID</center></td>
    <td width="113"><center>NOME</center></td>
    <td width="113"><center>ENDEREÇO</center></td>
    <td width="85"><center>CEP</center></td>
    <td width="85"><center>NÚMERO</center></td>
    <td width="85"><center>DATA DE CADASTRO</center></td>
    <td width="85"><center>DESCRIÇÃO</center></td>
    <td width="85"><center>BAIRRO</center></td>
    <td width="85"><center>CIDADE</center></td>
    
    <td width="85"><center>COMPLEMENTO</center></td>
    <td width="85"><center></center></td>

   <!-- <td width="85"><center>DESCRICAO</center></td>-->
  </tr>
   <?php 
        //var_dump($view_list);
        if(count($view_list)>0):?>
        <?php foreach ($view_list as $li):?>
  <tr>
    <td height="40" bgcolor="white "><?php echo $li->cod_local;?></td>
    <td bgcolor="white"><?php echo  $li->nome_loc;?></td>
    <td bgcolor="white "><?php echo $li->end_loc;?></td>
    <td bgcolor="white "><?php echo $li->cep_loc;?></td>
    <td bgcolor="white "><?php echo $li->nro_loc;?></td>
    <td bgcolor="white "><?php echo $li->data_cad_loc;?></td>
    <td bgcolor="white "><?php echo $li->desc_local;?></td>
    <td bgcolor="white "><?php echo $li->bairro_loc;?></td>
    <td bgcolor="white "><?php echo $li->cidade_loc;?></td>
    
    <td bgcolor="white "><?php echo $li->comp_loc;?></td>






    <!-- <td bgcolor="white "><?php// echo $li->desc_evento;?></td>-->
<td>
                <a href="notificacoes/excluirLocais/<?php echo $li->cod_local;?>/<?php echo $li->nome_loc;?>/<?php echo $this->getParams(1)?>" class="botao01">Deletar</a>
                <a href="notificacoes/formLocais/<?php echo $li->cod_local;?>/inserir/<?php echo $this->getParams(1)?>" class="botao01">Inserir</a>
            </td>
        </tr>
        <?php endforeach;?>
        <?php endif;?>
    </tbody>
</table>

