<?php if(isset($_SESSION['usuario']) and !empty($_SESSION['usuario'])){
    $session = strtoupper($_SESSION['usuario']);
    $id = $_SESSION['id'];
    $botaologin = 'Sair';
    $ahref1 = 'site/login/Sair';
    $botaocad = 'Meu Perfil';
     $ahref2 = 'site/perfil/usuario/'.$id;
    } else {
        $session = 'ENTRAR';
        $botaologin = 'Login';
        $ahref1 = 'site/login/';
        $botaocad = 'Cadastra-se';
         $ahref2 = 'site/cadastroUsuario/';
}?>
<!doctype html>
<html lang="pt-br">
     <head>
        <meta charset="utf-8">
         <base href="<?php echo APP_ROOT;?>">
        <link rel="shortcut icon" href="content/site/img/favicon.ico" type="image/x-icon">
<link rel="icon" href="content/site/img/favicon.ico" type="image/x-icon">
         <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">
     <style>
         #coroa{
             position: absolute;
             display:none;
         }    
         .form-control:invalid {
        border: 1px solid #cc0000;
      }
      .campo{
      border-color : #66CDAA;
      background: transparent;
      border-width: 2px 2px 2px 2px;;
      border-style: solid;
      border-radius: 10px;
      -moz-border-radius: 10px;
      -webkit-border-radius: 10px;
      padding: 7px;
     /* padding-right: 755px;*/}
                        #texto{
                            width: 95%;
                            
                        }
    
      .apert{
        color: #fff;
        background-color: #66CDAA;
        position: absolute;
        border-color: #66CDAA;
        border-width: 2px 2px 2px 2px;
        border-style: solid;
        border-radius: 0px 10px 10px 0px;
        -moz-border-radius: 0px 10px 10px 0px;
        -webkit-border-radius: 0px 10px 10px 0px;
        padding: 7px;
        left: 92%;
        }
        .teste{
          float: left;
          position: absolute;
          z-index: 9999;
        }
    </style>
    <title>TOK TO TRAVEL</title>
     
    <!--<[if lt IE 9]>-->
      <!--<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>-->
    <!--<![endif]-->
    <link rel="stylesheet" media="all" href="content/site/css/style.css"/>
    <meta name="viewport" content="width=device-width, initial-scale=1"/>
    <!-- Adding "maximum-scale=1" fixes the Mobile Safari auto-zoom bug: http://filamentgroup.com/examples/iosScaleBug/ -->    
        
    <!-- JS -->
            
    <script src="content/site/js/jquery-1.7.1.min.js"></script>
    <script src="content/site/js/custom.js"></script>
                <script src="content/site/js/tabs.js"></script>
    <script src="content/site/js/css3-mediaqueries.js"></script>
    <script src="content/site/js/jquery.columnizer.min.js"></script>
    
    <!-- Isotope -->
    <script src="content/site/js/jquery.isotope.min.js"></script>
    
    <!-- Lof slider -->
    <script src="content/site/js/jquery.easing.js"></script>
    <script src="content/site/js/lof-slider.js"></script>
    <link rel="stylesheet" href="content/site/css/lof-slider.css" media="all"  /> 
    <!-- ENDS slider -->
    
    <!-- Tweet -->
    <link rel="stylesheet" href="content/site/css/jquery.tweet.css" media="all"  /> 
    <script src="content/site/js/tweet/jquery.tweet.js" ></script> 
    <!-- ENDS Tweet -->
    
    <!-- superfish -->
    <link rel="stylesheet" media="screen" href="content/site/css/superfish.css" /> 
    <script  src="content/site/js/superfish-1.4.8/js/hoverIntent.js"></script>
    <script  src="content/site/js/superfish-1.4.8/js/superfish.js"></script>
    <script  src="content/site/js/superfish-1.4.8/js/supersubs.js"></script>
    <!-- ENDS superfish -->
    
    <!-- prettyPhoto -->
    <script  src="content/site/js/prettyPhoto/js/jquery.prettyPhoto.js"></script>
    <link rel="stylesheet" href="content/site/js/prettyPhoto/css/prettyPhoto.css"  media="screen" />
    <!-- ENDS prettyPhoto -->
    
    <!-- poshytip -->
    <link rel="stylesheet" href="content/site/js/poshytip-1.1/src/tip-twitter/tip-twitter.css"  />
    <link rel="stylesheet" href="content/site/js/poshytip-1.1/src/tip-yellowsimple/tip-yellowsimple.css"  />
    <script  src="content/site/js/poshytip-1.1/src/jquery.poshytip.min.js"></script>
    <!-- ENDS poshytip -->
    
    <!-- JCarousel -->
    <script type="text/javascript" src="content/site/js/jquery.jcarousel.min.js"></script>
    <link rel="stylesheet" media="screen" href="content/site/css/carousel.css" /> 
    <!-- ENDS JCarousel -->
    
    <!-- GOOGLE FONTS -->
    <link href='http://fonts.googleapis.com/css?family=Voltaire' rel='stylesheet' type='text/css'>

    <!-- modernizr -->
    <script src="content/site/js/modernizr.js"></script>
    
    <!-- SKIN -->
    <link rel="stylesheet" media="all" href="content/site/css/skin.css"/>
    
    <!-- Less framework -->
    <link rel="stylesheet" media="all" href="content/site/css/lessframework.css"/>
    
    <!-- flexslider -->
    <link rel="stylesheet" href="content/site/css/flexslider.css" >
    <script src="content/site/js/jquery.flexslider.js"></script>

    </head>
    <body class="home" >
       <header>
      <div class="wrapper cf">
                <div id="logo">
          <a href=""> <img  src="content/site/img/logo.png" alt="Simpler"></a>
        </div>

        
        <!-- nav -->
        <ul id="nav" class="sf-menu">
          <li class="current-menu-item"><a href="">INICIO</a></li>
          <li><a href="site/eventos/">EVENTOS</a></li>
                                        <li><a>COLABORE</a>
                                        <ul>
                                           <li><a href="site/cadastroLocais">Cadastrar Local</a></li>
                                            <li><a href="site/cadastroEventos/">Cadastrar Evento</a></li>
                                        </ul>
                                        </li>
          <li><a href="site/sobre/">SOBRE</a></li>
          <li><a href="site/contatos/">CONTATO</a></li>
                                        <li  class="entrar"><a><img id="coroa" src="content/site/img/coroa.png"/><?php echo $session;?></a>
          <ul>
              <li><a href="<?php echo $ahref1; ?>"><?php echo $botaologin;?></a></li>
              <li><a href="<?php echo $ahref2; ?>"><?php echo $botaocad;?></a></li>
              
          </ul>
          </li>
        </ul>
        <div id="combo-holder"></div>
          
                
        <div id="home-slider" class="lof-slidecontent">
          
          <div class="preload"><div></div></div>
          
          <!-- slider content --> 
          <div class="main-slider-content" >
          <ul class="sliders-wrap-inner">
              <li>
                    <img src="content/site/img/dummies/slides/01.jpg" title="" alt="alt" />           
                    <div class="slider-description">
                      <h4>Ponte Estaiada Octavio Frias de Oliveira</h4>
                      <p>A ponte Octávio Frias de Oliveira é um marco na arquitetura nacional, pois foi construída com um formato único no mundo: duas pontes em curva formando um X e sustentadas por estais ligados a um único mastro. Uma ponte estaiada é uma ponte suspe...
                      <a class="link" href="http://toktotravel.tecnologia.ws/site/locais/index/8">Ler mais</a>
                      </p>
                   </div>
              </li>
              
              <li>
                    <img src="content/site/img/dummies/slides/02.jpg" title="" alt="alt" />           
                    <div class="slider-description">
                      <h4>Estação da Luz</h4>
                      <p>A Estação da Luz é uma das mais importantes estações ferroviárias da cidade de São Paulo. Seu projeto foi feito por Charles Henry Driver , um arquiteto britânico conhecido por projetos em estações ferroviárias. A estação está localizada no Bom Reti...
                      <a class="link" href="http://toktotravel.tecnologia.ws/site/locais/index/4">Ler mais</a>
                      </p>
                   </div>
              </li>
              
              <li>
                    <img src="content/site/img/dummies/slides/03.jpg" title="" alt="alt" />           
                    <div class="slider-description">
                      <h4>Estádio do Pacaembu</h4>
                      <p>O Estádio Municipal Paulo Machado de Carvalho, mais conhecido por Estádio do Pacaembu ou simplesmente Pacaembu, é um estádio desportivo localizado na praça Charles Miller, no final da avenida Pacaembu, no final da avenida Pacaembu, no bairro do Pacaem...
                      <a class="link" href="http://toktotravel.tecnologia.ws/site/locais/index/32">Ler mais</a>
                      </p>
                   </div>
              </li>
              
              <li>
                    <img src="content/site/img/dummies/slides/04.jpg" title="" alt="alt" />           
                    <div class="slider-description">
                      <h4>Memorial da América Latina</h4>
                      <p>O Memorial da América Latina é um centro cultural, político e de lazer, inaugurado em 18 de março de 1989 na cidade de São Paulo, Brasil. O conjunto arquitetônico, projetado por Oscar Niemeyer, é um monumento à integração cultural, política, econômi...
                      <a class="link" href="#">Ler mais</a>
                      </p>
                   </div>
              </li>
              
              <li>
                    <img src="content/site/img/dummies/slides/05.jpg" title="" alt="alt" />           
                    <div class="slider-description">
                      <h4>Museu de Arte de São Paulo</h4>
                      <p>Museu de Arte de São Paulo Assis Chateaubriand (mais conhecido pelo acrônimo MASP) é uma das mais importantes instituições culturais brasileiras.[2] Localiza-se, desde 7 de novembro de 1968, na Avenida Paulista, cidade de São Paulo, em um edifício projet...
                      <a class="link" href="http://toktotravel.tecnologia.ws/site/locais/index/9">Ler mais</a>
                      </p>
                   </div>
              </li>
              
              <li>
                    <img src="content/site/img/dummies/slides/06.jpg" title="" alt="alt" />           
                    <div class="slider-description">
                      <h4>Catedral da Sé</h4>
                      <p>Em 1913, iniciou-se a construção da Catedral como é hoje, elaborada pelo alemão Maximilian Emil Hehl, professor de Arquitetura da Escola Politécnica. O templo foi inaugurado em 25 de janeiro de 1954, na comemoração do 4º Centenário da Cidade de São Paulo, ainda se...
                      <a class="link" href="http://toktotravel.tecnologia.ws/site/locais/index/2">Ler mais</a>
                      </p>
                   </div>
              </li>
              
              <li>
                    <img src="content/site/img/dummies/slides/07.jpg" title="" alt="alt" />           
                    <div class="slider-description">
                      <h4>Monumento às Bandeiras</h4>
                      <p>O Monumento ás Bandeiras é uma obra em homenagem aos Bandeirantes, que desbravavam os sertões durante os séculos XVII e XVIII. Foi inaugurada no ano de 1953, fazendo parte das comemorações do IV Centenário da cidade de São Paulo...
                      <a class="link" href="http://toktotravel.tecnologia.ws/site/locais/index/6">Ler mais</a>
                      </p>
                   </div>
          </li>
        </ul>
          <div class="navigator-content">
            <div class="navigator-wrapper">
                  <ul class="navigator-wrap-inner">
                     <li><img src="content/site/img/dummies/slides/01_thumb.jpg" alt="alt" /></li>
                     <li><img src="content/site/img/dummies/slides/02_thumb.jpg" alt="alt" /></li>
                     <li><img src="content/site/img/dummies/slides/03_thumb.jpg" alt="alt" /></li>
                     <li><img src="content/site/img/dummies/slides/04_thumb.jpg" alt="alt" /></li>
                     <li><img src="content/site/img/dummies/slides/05_thumb.jpg" alt="alt" /></li>
                     <li><img src="content/site/img/dummies/slides/06_thumb.jpg" alt="alt" /></li>
                     <li><img src="content/site/img/dummies/slides/07_thumb.jpg" alt="alt" /></li>
                  </ul>
            </div>
            <div class="button-next">Next</div>
            <div  class="button-previous">Previous</div>
            <!-- REMOVED TILL FIXED <div class="button-control"><span>STOP</span></div> -->
        </div> 
      </div>
    </header>
        <?php if(isset($_SESSION['tipo']) && $_SESSION['tipo']=='VIP'){
                                        echo " <script>$('#coroa').css('display','block');</script>";}?>
        <?php $this->Render(); ?>
          <footer>
                    <?php $footer = $this->carregarFooter();?>
                    
      <div class="wrapper cf">
      
        <!-- widgets -->
        <ul  class="widget-cols cf">
          <li class="first-col">
            
            <div class="widget-block">
              <h4>EVENTOS ATUAIS</h4>
                                                         <?php                                                    foreach ($footer as $eventos){?>
              <div class="recent-post cf">
                <a href="site/eventos/eventos/<?php echo $eventos->cod_evento;?>" class="thumb"><img src="<?php echo $eventos->caminho_img;?>" width = "120px" alt="Post" /></a>
                <div class="post-head">
                                                                    <span><a href="site/eventos/eventos/<?php echo $eventos->cod_evento;?>"><?php echo $eventos->nome_evento;?></a><span><?php echo $eventos->data_evento;?></span><span><?php echo $eventos->hr_evento;?></span>
                </div>
              </div>
                                                         <?php }?>
            </div>
          </li>
          
          <li class="second-col">
            
            <div class="widget-block">
              <h4>SOBRE</h4>
              <a href="http://toknology.tecnologia.ws"><img src="content/site/img/logoapp.png" width = "140px"></a><p>A Toknology é uma empresa de desenvolvimento de softwares</p> 
              <p>Que tem o compromisso de encontrar facilidades e comodidade para atender nossos clientes</p>
            </div>
            
          </li>
          
          <li class="third-col">
                 
          </li>
          
          <li class="fourth-col">
            
            <div class="widget-block">
              <h4>MENU</h4>
              <ul>
                <li class="cat-item"><a href="" >INICIO</a></li>
                <li class="cat-item"><a href="site/sobre/" >SOBRE</a></li>
                <li class="cat-item"><a href="site/eventos/">EVENTOS</a></li>
                <li class="cat-item"><a href="site/contatos" >CONTATO</a></li>
                <li class="cat-item"><a href="site/parceiro/" >SEJA UM PARCEIRO</a></li>
        <li class="cat-item"><a href="content/site/arquivos/ToktoTravel.apk" >BAIXE NOSSO APP</a></li>  

              </ul>
            </div>
                 
          </li>  
        </ul>
        <!-- ENDS widgets -->  
        
        
        <!-- bottom -->
        <div class="footer-bottom">
          <div class="left">BY <a href="http://toknology.tecnologia.ws" >TOKNOLOGY</a></div>
            <ul id="social-bar" class="cf sb">
            <li><a href="http://www.facebook.com"  title="Facebook"><img src="content/site/img/facebook.png" width  = "60px" height="66px"></a></li>
            <li><a href="https://twitter.com/TOKNOLOGYETEC" title="Twitter"><img src="content/site/img/twitter.png" width  = "60px" height ="66px"> </a></li>
            <li><a href="https://www.instagram.com/?hl=pt-br" title="Instagram"><img src="content/site/img/instagram.png" width  = "60px" height ="66px"></a></li>
            <li><a href="http://plus.google.com" title="Google"><img src="content/site/img/gmail.png" width  = "60px" height ="66px"></a></li>
            </ul>
        </div>  
        <!-- ENDS bottom -->
      
      </div>
    </footer>
    </body>

</html>