<!doctype html>
<html lang="pt-br">
<head>
	<meta charset ="utf-8">
        <base href="<?php echo APP_ROOT;?>">
	<title>Tela Login</title>
        <meta name="google-signin-scope" content="profile email">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
	<!--<script src="https://apis.google.com/js/platform.js" async defer></script>
        <meta name="google-signin-client_id" content="292271043599-eettkao6tlq18ee2qm4b6l60m5etqov9.apps.googleusercontent.com">-->
	<link rel="stylesheet" href="content/admin/css/logincss.css"/>
</head>
<body>
<?php $this->Render();?>
    </body>
</html>
