<!doctype html>
<html lang="pt-br">
<head>
	<meta charset ="utf-8">
	<title>Tela Login</title>
          <base href="<?php echo APP_ROOT;?>">
        <style>
            body
{
	margin:0;
	padding:0;
	background:url(content/admin/img/estacaodaluz.jpg) no-repeat;
	font-family: sans-serif;
        background-size: cover;
}
.loginbox{
	position: absolute;
	top:50%;
	left: 50%;
	transform: translate(-50%, -50%);
	width: 350px;
	height: 450px;
	padding:80px 40px;
	box-sizing: border-box;
	background: rgba(0,0,0,.5);
}
.user{
	
	width:100px;
	height:100px;
	border-radius:50%;
	overflow: hidden;
	position: absolute;
	top: calc(-100px/2);
	left: calc(50% - 50px);	
}
h2{
	margin:0;
	padding:0 0 20px;
	color:#fff;
	text-align: center;
}
.loginbox p{
	margin:0;
	padding:0;
	font-weight: bold;
	color:#fff;
}
.loginbox input{
	width: 100%;
	margin: 20px;
}
.loginbox input[type="text"],
.loginbox input[type="password"]
{
	border:none;
	border-bottom: 1px solid #fff;
	background:transparent;
	outline: none;
	height:40px;
	color:#fff;
	font-size:16px;
}
::placeholder
{
	color: rgba(255,255,255,.5);
}
.loginbox input[type="submit"]
{
	border: none;
	outline:none;
	height:30px;
	color:#000;
	font-size:16px;
	background:#CFCFCF;
	cursor: pointer;
	border-radius: 20px;
}
.loginbox input[type="submit"]:hover
{
	background:#00688B;
	color:#fff;
}
.loginbox a
{
	color: #fff;
	font-size: 14px;
	font-weight: bold;
	text-decoration:none;
}

button#face{
	margin:0px 0px 0px 40px;
	border:none;
	outline:none;
	height:38px;
	color:#fff;
	font-size:16px;
	background:rgb(59,89,152);
	cursor: pointer;
	font-weight:bold;
	position:relative;
	bottom:37px;
	left:90px;
}
button#face img{
	padding-left:-20px;
	padding-right:20px;
}
button#face:hover{
	border: .5px solid rgba(255,255,255,1);
	box-shadow: 1px 1px 5px white;
}
        </style>	
</head>
<body>
<?php $this->Render();?>
    </body>
</html>

