<!doctype html>
<html lang="pt-br">
    <head>
        <meta charset="utf-8">
         <base href="<?php echo APP_ROOT;?>">
         <style>
			.form-control:invalid {
				border: 1px solid #cc0000;
			}
			.campo{
			border-color : #66CDAA;
			background: transparent;
			border-width: 2px 2px 2px 2px;;
			border-style: solid;
			border-radius: 10px;
			-moz-border-radius: 10px;
			-webkit-border-radius: 10px;
			padding: 7px;
			padding-right: 755px;}
		
			.apert{
				color: #fff;
				background-color: #66CDAA;
				position: absolute;
				border-color: #66CDAA;
				border-width: 2px 2px 2px 2px;
				border-style: solid;
				border-radius: 0px 10px 10px 0px;
				-moz-border-radius: 0px 10px 10px 0px;
				-webkit-border-radius: 0px 10px 10px 0px;
				padding: 7px;
				left: 884px;
				}
		</style>
		<title>TOK TO TRAVEL</title>
		 
		<!--<[if lt IE 9]>-->
			<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
		<!--<![endif]-->
		<link rel="stylesheet" media="all" href="content/site/css/style.css"/>
		<meta name="viewport" content="width=device-width, initial-scale=1"/>
		<!-- Adding "maximum-scale=1" fixes the Mobile Safari auto-zoom bug: http://filamentgroup.com/examples/iosScaleBug/ -->		
				
		<!-- JS -->
		<script src="content/site/js/jquery-1.7.1.min.js"></script>
		<script src="content/site/js/custom.js"></script>
		<script src="content/site/js/tabs.js"></script>
		<script src="content/site/js/css3-mediaqueries.js"></script>
		<script src="content/site/js/jquery.columnizer.min.js"></script>
		
		<!-- Isotope -->
		<script src="content/site/js/jquery.isotope.min.js"></script>
		
		<!-- Lof slider -->
		<script src="content/site/js/jquery.easing.js"></script>
		<script src="content/site/js/lof-slider.js"></script>
		<link rel="stylesheet" href="content/site/css/lof-slider.css" media="all"  /> 
		<!-- ENDS slider -->
		
		<!-- Tweet -->
		<link rel="stylesheet" href="content/site/css/jquery.tweet.css" media="all"  /> 
		<script src="content/site/js/tweet/jquery.tweet.js" ></script> 
		<!-- ENDS Tweet -->
		
		<!-- superfish -->
		<link rel="stylesheet" media="screen" href="content/site/css/superfish.css" /> 
		<script  src="content/site/js/superfish-1.4.8/js/hoverIntent.js"></script>
		<script  src="content/site/js/superfish-1.4.8/js/superfish.js"></script>
		<script  src="content/site/js/superfish-1.4.8/js/supersubs.js"></script>
		<!-- ENDS superfish -->
		
		<!-- prettyPhoto -->
		<script  src="content/site/js/prettyPhoto/js/jquery.prettyPhoto.js"></script>
		<link rel="stylesheet" href="content/site/js/prettyPhoto/css/prettyPhoto.css"  media="screen" />
		<!-- ENDS prettyPhoto -->
		
		<!-- poshytip -->
		<link rel="stylesheet" href="content/site/js/poshytip-1.1/src/tip-twitter/tip-twitter.css"  />
		<link rel="stylesheet" href="content/site/js/poshytip-1.1/src/tip-yellowsimple/tip-yellowsimple.css"  />
		<script  src="content/site/js/poshytip-1.1/src/jquery.poshytip.min.js"></script>
		<!-- ENDS poshytip -->
		
		<!-- JCarousel -->
		<script type="text/javascript" src="content/site/js/jquery.jcarousel.min.js"></script>
		<link rel="stylesheet" media="screen" href="content/site/css/carousel.css" /> 
		<!-- ENDS JCarousel -->
		
		<!-- GOOGLE FONTS -->
		<link href='http://fonts.googleapis.com/css?family=Voltaire' rel='stylesheet' type='text/css'>

		<!-- modernizr -->
		<script src="content/site/js/modernizr.js"></script>
		
		<!-- SKIN -->
		<link rel="stylesheet" media="all" href="content/site/css/skin.css"/>
		
		<!-- Less framework -->
		<link rel="stylesheet" media="all" href="content/site/css/lessframework.css"/>
		
		<!-- flexslider -->
		<link rel="stylesheet" href="content/site/css/flexslider.css" >
		<script src="content/site/js/jquery.flexslider.js"></script>

    </head>
    <body  class="home">
        <?php $this->Render(); ?>
    </body>
</html>
