<?php 
//include 'loginfacebook.phtml';
//error_reporting(0);
?> 
<script>
                                    $(document).ready(function(){
                                         $("li").removeClass('current-menu-item');
                                        $(".entrar").addClass('current-menu-item');
 });
                                    </script>
<div class="loginBox">
		<form action="login/validar" method="POST">
		<br>
		<br>
		<center><div class="box1"><h1>Login<h1></div><br></center>
		<br>
		<br>
		
		<center><label for="login"><h3>Usuário<h3></label></center><br>
                                <center><input type="text" class="input-class" id="login" name="usuario" placeholder="Digite seu Usuário"/><br></center>
				<center><label for="senha"><h3>Senha<h3></label></center>
				<center><input type="password" class="input-class" id="senha" name="senha" placeholder="*******"/><br></center><br>
				<center><input type="submit" name="btnfazer" id="btnEnviar" value="Entrar" class="send"/></center>
				<br>
				
                </form>
    <p id="msg"><?php if(isset($_SESSION['msg'])){ echo $_SESSION['msg']; unset ($_SESSION['msg']); }?></p>
            		<!--<a href="<?php //echo $loginUrl;?>"/><button type="button" id="face"><img src="img/Facebook_logo.png">Facebook</button></a><br>-->
		<!--<center><a><p>ESQUECEU A SENHA?</p></a></center>-->
		
</div>

