 <script>
                                    $(document).ready(function(){
                                         $("li").removeClass('current-menu-item');
                                        $(".sobre").addClass('current-menu-item');
 });
                                    </script>
			<div id="main">
			<div class="wrapper cf">
			
			
				
			<!-- page content-->
        	<div id="page-content" class="cf">        	
	        		
	        		
				<!-- entry-content -->	
	        	<div class="entry-content cf">
					
					
			    
					<!-- Tabs -->
					<h2 class="heading">Conheça-nos</h2>

					<ul class="tabs">
						<li><a href="#"><span>Quem somos</span></a></li>
						<li><a href="#"><span>O Aplicativo</span></a></li>
						
					</ul>
	
					<div class="panes">
						<div>
							<p>O Tok To Travel foi criado pela empresa Toknology, uma pequena empresa gerada por alguns alunos do segundo módulo do curso de informática da ETEC Professor Horácio Augusto da Silveira no segundo semestre de 2017. A empresa nasceu para a realização do TCC desses alunos, tendo como foco o desenvolvimento de Softwares que facilitem o dia a dia das pessoas.
							<br><br>Conheça-nos melhor: <a href="http://toknology.tecnologia.ws"> Toknology</a> </p>
	
						</div>
						<div>
							<p>O aplicativo Tok To Travel nasceu de um projeto de tcc em meados de junho de 2017, porém só saiu do papel em fevereiro de 2018. A meta do projeto é proporcionar  diversas opções e auxiliar com informações sobre os locais, atrações e transporte em viagens e passeios no estado de São Paulo.<br>
							<br>Temos como diferenciais:
							<ul>
							<li>• Utilização fácil</li>
							<li>• Interface amigável ao usuário</li> 
							<li>• Facilidade na busca</li>
							<ul>
						</div>
						
						
					</div>
					<!-- ENDS TABS -->	
					
				     
				     
				     
				    <div class="toggle-trigger">Nossa Missão</div>		
					<div class="toggle-container">
						Garantir a satisfação do cliente com soluções criativas, ideias inovadoras e serviços de qualidade que superem suas expectativas;
					</div>
										
					<div class="toggle-trigger">Nossa Visão</div>			
					<div class="toggle-container">
						Ser uma empresa de referência no setor de software conquistando relacionamentos duradouros e entregando o melhor produto.
					</div>
					
					<div class="toggle-trigger">Nossos Valores</div>			
					<div class="toggle-container">
						Responsabilidade, dedicação, confiabilidade, praticidade.
					</div>
				    <!-- ENDS Toggle -->
				    
				      
				</div>
				<!-- entry-content -->	
				
				
    		</div>
    		<!-- ENDS page content-->
			
			
			
			</div><!-- ENDS WRAPPER -->
		</div>