<?php if($view_return == 'erro') { ?>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<center><h1>Erro</h1></center>
<center><img src="content/site/img/robot-msg-error.png"></center>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<?php } else { ?>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<center><h1>Enviado com Sucesso</h1></center>
<center><img src="content/site/img/envelope.png"></center>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>
<?php } ?>




